#!/usr/bin/env bash
# Bash script that Install nginx web server
# and change the index file content

sudo apt-get update
sudo apt-get install -y nginx
sudo echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo /etc/init.d/nginx restart
