#!/usr/bin/env bash
# Bash script to configure a web server and contains a custom header
sudo apt update
sudo apt install -y nginx
sudo ufw allow "Nginx HTTP"
sudo echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i '53 a \\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sudo sed -i '56 a \\terror_page 404 /custom_404.html;' /etc/nginx/sites-available/default
sudo sed '/^\tserver_name _;/ a \\tadd_header X-Served-By \$hostname;' /etc/nginx/sites-available/default
sudo /etc/init.d/nginx restart
