#!/usr/bin/env bash
# Bash script to install load balancer
sudo apt update
sudo apt install -y haproxy

sudo echo -e "
frontend haproxy-main
\tbind *:80
\tdefault_backend webservers

backend webservers
\tbalance roundrobin
\tserver 7422-web-01\t18.206.238.207:80 check
\tserver 7422-web-02\t44.197.196.98:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
